document.write("<!DOCTYPE html>");
document.write("<html style=\"font-size: 16px;\" lang=\"pt\">");
document.write("  <head>");
document.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
document.write("    <meta charset=\"utf-8\">");
document.write("    <meta name=\"keywords\" content=\"​Quem sou eu?, ​Meus projetos, ​Recorram a Jeová Deus\">");
document.write("    <link rel=\"shortcut icon\" href=\"images\/1703183666890logo.png\" type=\"image\/x-icon\"\/>");
document.write("    <meta name=\"description\" content=\"\">");
document.write("    <title>Portfólio Paulo jorge<\/title>");
document.write("    <meta content=\"https:\/\/pjxsantos.github.io\/images\/paulo.jpg\" property=\"og:image\"\/>");
document.write("    <meta content=\"Crio web designs personalizados. Tenho habilidade em escrever códigos bem projetados, testáveis ​​e eficientes usando as melhores práticas atuais em desenvolvimento Web. Aprendo rápido, trabalho duro e trabalho em equipe, com proficiência na criação de páginas da web criativas e inovadoras.\" name=\"description\"\/>");
document.write("    <link rel=\"stylesheet\" href=\"css\/style.css\" media=\"screen\">");
document.write("    <link rel=\"stylesheet\" href=\"css\/Pjxsantos.css\" media=\"screen\">");
document.write("    <script class=\"u-script\" type=\"text\/javascript\" src=\"js\/jquery-1.9.1.min.js\" defer=\"\"><\/script>");
document.write("    <script class=\"u-script\" type=\"text\/javascript\" src=\"js\/script.js\" defer=\"\"><\/script>");
document.write("    <meta name=\"generator\" content=\"V 2.0, Pjxsantos\">");
document.write("    <link id=\"u-theme-google-font\" rel=\"stylesheet\" href=\"https:\/\/fonts.googleapis.com\/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i\">");
document.write("    <link id=\"u-page-google-font\" rel=\"stylesheet\" href=\"https:\/\/fonts.googleapis.com\/css?family=Amarante:400\">");
document.write("    <script type=\"application\/ld+json\">{");
document.write("      \"@context\": \"http:\/\/schema.org\",");
document.write("      \"@type\": \"Organization\",");
document.write("      \"name\": \"\",");
document.write("      \"url\": \"\/\",");
document.write("      \"logo\": \"images\/1703183666890logo.png\",");
document.write("      \"sameAs\": [");
document.write("      		\"https:\/\/github.com\/Pjxsantos\/\",");
document.write("      		\"https:\/\/www.mapacultural.pe.gov.br\/agente\/21825\/\",");
document.write("      		\"https:\/\/www.linkedin.com\/in\/pjxsantos\/\"");
document.write("      ]");
document.write("      }");
document.write("    <\/script>");
document.write("    <meta name=\"theme-color\" content=\"#8700ff\">");
document.write("    <meta property=\"og:title\" content=\"Portfólio Paulo jorge\">");
document.write("    <meta property=\"og:type\" content=\"website\">");
document.write("    <link rel=\"canonical\" href=\"\/\">");
document.write("    <meta data-intl-tel-input-cdn-path=\"intlTelInput\/\">");
document.write("  <\/head>");
document.write("  <body data-home-page=\"#\" data-home-page-title=\"Pjxsantos\" data-path-to-root=\".\/\" data-include-products=\"false\" class=\"u-body u-xl-mode\" data-lang=\"pt\">");
document.write("    <header class=\"u-clearfix u-gradient u-header u-sticky u-sticky-55bf u-header\" id=\"sec-c4bb\">");
document.write("      <div class=\"u-clearfix u-sheet u-valign-middle-md u-sheet-1\">");
document.write("        <a href=\"#\" class=\"u-image u-logo u-image-1\" data-image-width=\"376\" data-image-height=\"245\" title=\"Logo\">");
document.write("        <img src=\"images\/1703183666890logo.png\" class=\"u-logo-image u-logo-image-1\">");
document.write("        <\/a>");
document.write("        <nav class=\"u-menu u-menu-dropdown u-offcanvas u-menu-1\" data-submenu-level=\"with-reload\">");
document.write("          <div class=\"menu-collapse\" style=\"font-size: 1rem; letter-spacing: 0px; text-transform: uppercase; font-weight: 500;\">");
document.write("            <a class=\"u-button-style u-custom-active-border-color u-custom-active-color u-custom-border u-custom-border-color u-custom-border-radius u-custom-borders u-custom-color u-custom-hover-border-color u-custom-hover-color u-custom-left-right-menu-spacing u-custom-padding-bottom u-custom-text-active-color u-custom-text-color u-custom-text-decoration u-custom-text-hover-color u-custom-text-shadow u-custom-top-bottom-menu-spacing u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base\" href=\"#\" style=\"\">");
document.write("              <svg class=\"u-svg-link\" viewBox=\"0 0 24 24\">");
document.write("                <use xlink:href=\"#menu-hamburger\"><\/use>");
document.write("              <\/svg>");
document.write("              <svg class=\"u-svg-content\" version=\"1.1\" id=\"menu-hamburger\" viewBox=\"0 0 16 16\" x=\"0px\" y=\"0px\" xmlns:xlink=\"http:\/\/www.w3.org\/1999\/xlink\" xmlns=\"http:\/\/www.w3.org\/2000\/svg\">");
document.write("                <g>");
document.write("                  <rect y=\"1\" width=\"16\" height=\"2\"><\/rect>");
document.write("                  <rect y=\"7\" width=\"16\" height=\"2\"><\/rect>");
document.write("                  <rect y=\"13\" width=\"16\" height=\"2\"><\/rect>");
document.write("                <\/g>");
document.write("              <\/svg>");
document.write("            <\/a>");
document.write("          <\/div>");
document.write("          <div class=\"u-custom-menu u-nav-container\">");
document.write("            <ul class=\"u-nav u-spacing-2 u-unstyled u-nav-1\">");
document.write("              <li class=\"u-nav-item\">");
document.write("                <a class=\"u-active-custom-color-3 u-border-2 u-border-active-white u-border-white u-button-style u-custom-color-5 u-hover-custom-color-3 u-nav-link u-radius u-text-active-white u-text-body-alt-color u-text-hover-white\" href=\"#\" style=\"--radius: 10px; padding: 10px 20px;\">Cursos<\/a>");
document.write("                <div class=\"u-nav-popup\">");
document.write("                  <ul class=\"u-border-2 u-border-white u-h-spacing-20 u-nav u-unstyled u-v-spacing-10\">");
document.write("                    <li class=\"u-nav-item\"><a class=\"u-active-custom-color-5 u-button-style u-custom-color-3 u-hover-custom-color-5 u-nav-link\" href=\"https:\/\/www.ev.org.br\/cursos\">Fundação Bradesco<\/a><\/li>");
document.write("                    <li class=\"u-nav-item\"><a class=\"u-active-custom-color-5 u-button-style u-custom-color-3 u-hover-custom-color-5 u-nav-link\" href=\"https:\/\/www.jw.org\/pt\/ensinos-biblicos\/curso-biblia-instrutor\/\">CURSO DA BÍBLIA<\/a><\/li>");
document.write("                  <\/ul>");
document.write("                <\/div>");
document.write("              <\/li>");
document.write("              <li class=\"u-nav-item\"><a class=\"u-active-custom-color-3 u-border-2 u-border-active-white u-border-white u-button-style u-custom-color-5 u-hover-custom-color-3 u-nav-link u-radius u-text-active-white u-text-body-alt-color u-text-hover-white\" href=\"index.html#sec-b1c4\" style=\"--radius: 10px; padding: 10px 20px;\">Projetos<\/a><\/li>");
document.write("              <li class=\"u-nav-item\"><a class=\"u-active-custom-color-3 u-border-2 u-border-active-white u-border-white u-button-style u-custom-color-5 u-hover-custom-color-3 u-nav-link u-radius u-text-active-white u-text-body-alt-color u-text-hover-white\" href=\"index.html#carousel_c8ff\" style=\"--radius: 10px; padding: 10px 20px;\">Biografia<\/a><\/li>");
document.write("            <\/ul>");
document.write("          <\/div>");
document.write("          <div class=\"u-custom-menu u-nav-container-collapse\">");
document.write("            <div class=\"u-border-20 u-border-custom-color-5 u-container-style u-custom-color-4 u-inner-container-layout u-opacity u-opacity-85 u-sidenav\">");
document.write("              <div class=\"u-inner-container-layout u-sidenav-overflow\">");
document.write("                <div class=\"u-menu-close\"><\/div>");
document.write("                <ul class=\"u-align-center u-custom-font u-nav u-popupmenu-items u-spacing-10 u-text-body-alt-color u-unstyled u-nav-3\">");
document.write("                  <li class=\"u-nav-item\">");
document.write("                    <a class=\"u-button-style u-nav-link\" href=\"https:\/\/www.jw.org\/pt\/ensinos-biblicos\/curso-biblia-instrutor\/\">Cursos<\/a>");
document.write("                    <div class=\"u-nav-popup\">");
document.write("                      <ul class=\"u-border-2 u-border-white u-h-spacing-20 u-nav u-unstyled u-v-spacing-10\">");
document.write("                        <li class=\"u-nav-item\"><a class=\"u-button-style u-nav-link\" href=\"https:\/\/www.ev.org.br\/cursos\">Fundação Bradesco<\/a><\/li>");
document.write("                        <li class=\"u-nav-item\"><a class=\"u-button-style u-nav-link\" href=\"https:\/\/www.jw.org\/pt\/ensinos-biblicos\/curso-biblia-instrutor\/\">CURSO DA BÍBLIA<\/a><\/li>");
document.write("                      <\/ul>");
document.write("                    <\/div>");
document.write("                  <\/li>");
document.write("                  <li class=\"u-nav-item\"><a class=\"u-button-style u-nav-link\" href=\"index.html#sec-b1c4\">Projetos<\/a><\/li>");
document.write("                  <li class=\"u-nav-item\"><a class=\"u-button-style u-nav-link\" href=\"index.html#carousel_c8ff\">Biografia<\/a><\/li>");
document.write("                <\/ul>");
document.write("              <\/div>");
document.write("            <\/div>");
document.write("            <div class=\"u-black u-menu-overlay u-opacity u-opacity-70\"><\/div>");
document.write("          <\/div>");
document.write("        <\/nav>");
document.write("      <\/div>");
document.write("    <\/header>");
document.write("    <section class=\"u-align-center u-clearfix u-custom-color-5 u-section-1\" id=\"carousel_5f6d\">");
document.write("      <div class=\"u-clearfix u-sheet u-sheet-1\">");
document.write("        <h4 class=\"u-custom-font u-text u-text-1\" data-animation-name=\"customAnimationIn\" data-animation-duration=\"1500\" data-animation-delay=\"500\"> Um pouco sobre mim<\/h4>");
document.write("        <h2 class=\"u-hover-feature u-text u-text-white u-text-2\" data-animation-name=\"customAnimationIn\" data-animation-duration=\"1500\" data-animation-delay=\"500\"> Quem sou eu?<\/h2>");
document.write("        <p class=\"u-text u-text-body-alt-color u-text-3\" data-animation-name=\"customAnimationIn\" data-animation-duration=\"1500\" data-animation-delay=\"500\"> Olá, meu nome é Paulo Jorge crio web designs personalizados. Tenho habilidade em escrever códigos bem projetados, testáveis ​e eficientes usando as melhores práticas atuais em desenvolvimento Web. Aprendo rápido, trabalho duro e trabalho em equipe, com proficiência na criação de páginas da web criativas e inovadoras.<\/p>");
document.write("        <div class=\"data-layout-selected u-clearfix u-expanded-width u-layout-wrap u-layout-wrap-1\">");
document.write("          <div class=\"u-layout\">");
document.write("            <div class=\"u-layout-row\">");
document.write("              <div class=\"u-align-center u-black u-container-style u-layout-cell u-opacity u-opacity-40 u-radius u-shape-round u-size-27-lg u-size-27-xl u-size-60-md u-size-60-sm u-size-60-xs u-layout-cell-1\" data-animation-name=\"customAnimationIn\" data-animation-duration=\"1500\" data-animation-delay=\"250\">");
document.write("                <div class=\"u-border-5 u-border-white u-container-layout u-valign-middle u-container-layout-1\">");
document.write("                  <div class=\"u-border-5 u-border-white u-hover-feature u-image u-image-circle u-preserve-proportions u-image-1\" alt=\"\" data-image-width=\"876\" data-image-height=\"897\"><\/div>");
document.write("                  <h3 class=\"u-text u-text-4\"> “Não é a linguagem de programação que define o programador, mas sim sua lógica.”<\/h3>");
document.write("                  <a href=\"https:\/\/github.com\/Pjxsantos\/\" class=\"u-active-white u-align-center u-border-active-white u-border-hover-white u-border-none u-btn u-btn-round u-button-style u-gradient u-hover-feature u-hover-white u-none u-radius u-text-active-custom-color-3 u-text-hover-white u-btn-1\" data-animation-name=\"\" data-animation-duration=\"0\" data-animation-delay=\"0\" data-animation-direction=\"\">Saber mais<\/a>");
document.write("                <\/div>");
document.write("              <\/div>");
document.write("              <div class=\"u-align-right u-container-style u-layout-cell u-size-33-lg u-size-33-xl u-size-60-md u-size-60-sm u-size-60-xs u-layout-cell-2\">");
document.write("                <div class=\"u-container-layout u-container-layout-2\">");
document.write("                  <div class=\"u-expanded-width-md u-expanded-width-sm u-expanded-width-xs u-list u-list-1\">");
document.write("                    <div class=\"u-repeater u-repeater-1\">");
document.write("                      <div class=\"u-align-left u-black u-border-10 u-border-custom-color-1 u-border-no-left u-border-no-right u-border-no-top u-container-style u-custom-item u-list-item u-opacity u-opacity-40 u-radius u-repeater-item u-shape-round u-list-item-1\" data-animation-name=\"customAnimationIn\" data-animation-duration=\"1500\" data-animation-delay=\"250\">");
document.write("                        <div class=\"u-container-layout u-similar-container u-valign-middle u-container-layout-3\">");
document.write("                          <span class=\"u-custom-item u-file-icon u-hover-feature u-icon u-icon-1\" data-animation-name=\"customAnimationIn\" data-animation-duration=\"1500\" data-animation-delay=\"750\"><img src=\"images\/1051277.png\" alt=\"\"><\/span>");
document.write("                          <h4 class=\"u-text u-text-5\">html<\/h4>");
document.write("                          <a href=\"https:\/\/github.com\/topics\/html\" class=\"u-border-active-grey-70 u-border-hover-grey-70 u-border-none u-bottom-left-radius-0 u-bottom-right-radius-0 u-btn u-btn-round u-button-style u-custom-item u-gradient u-none u-radius u-text-active-white u-text-body-color u-text-hover-white u-top-left-radius-0 u-top-right-radius-0 u-btn-2\"> mais<\/a>");
document.write("                        <\/div>");
document.write("                      <\/div>");
document.write("                      <div class=\"u-align-left u-black u-border-10 u-border-no-left u-border-no-right u-border-no-top u-border-palette-1-base u-container-style u-custom-item u-list-item u-opacity u-opacity-40 u-radius u-repeater-item u-shape-round u-video-cover u-list-item-2\" data-animation-name=\"customAnimationIn\" data-animation-duration=\"1500\" data-animation-delay=\"250\">");
document.write("                        <div class=\"u-container-layout u-similar-container u-valign-middle u-container-layout-4\">");
document.write("                          <span class=\"u-custom-item u-file-icon u-hover-feature u-icon u-icon-2\" data-animation-name=\"customAnimationIn\" data-animation-duration=\"1500\" data-animation-delay=\"750\"><img src=\"images\/732190.png\" alt=\"\"><\/span>");
document.write("                          <h4 class=\"u-text u-text-6\">css<\/h4>");
document.write("                          <a href=\"https:\/\/github.com\/topics\/css\" class=\"u-border-active-grey-70 u-border-black u-border-hover-grey-70 u-border-none u-bottom-left-radius-0 u-bottom-right-radius-0 u-btn u-btn-round u-button-style u-custom-item u-gradient u-none u-radius u-text-active-white u-text-body-color u-text-hover-white u-top-left-radius-0 u-top-right-radius-0 u-btn-3\"> mais<\/a>");
document.write("                        <\/div>");
document.write("                      <\/div>");
document.write("                      <div class=\"u-align-left u-black u-border-10 u-border-no-left u-border-no-right u-border-no-top u-border-palette-3-base u-container-style u-custom-item u-list-item u-opacity u-opacity-40 u-radius u-repeater-item u-shape-round u-video-cover u-list-item-3\" data-animation-name=\"customAnimationIn\" data-animation-duration=\"1500\" data-animation-delay=\"250\">");
document.write("                        <div class=\"u-container-layout u-similar-container u-valign-middle u-container-layout-5\">");
document.write("                          <span class=\"u-custom-item u-file-icon u-hover-feature u-icon u-icon-3\" data-animation-name=\"customAnimationIn\" data-animation-duration=\"1500\" data-animation-delay=\"750\"><img src=\"images\/1199124.png\" alt=\"\"><\/span>");
document.write("                          <h4 class=\"u-text u-text-7\">javascript<\/h4>");
document.write("                          <a href=\"https:\/\/github.com\/topics\/react\" class=\"u-border-active-grey-70 u-border-black u-border-hover-grey-70 u-border-none u-bottom-left-radius-0 u-bottom-right-radius-0 u-btn u-button-style u-custom-item u-gradient u-none u-radius-0 u-text-active-white u-text-body-color u-text-hover-white u-top-left-radius-0 u-top-right-radius-0 u-btn-4\"> mais<\/a>");
document.write("                        <\/div>");
document.write("                      <\/div>");
document.write("                      <div class=\"u-align-left u-black u-border-10 u-border-no-left u-border-no-right u-border-no-top u-border-palette-1-light-1 u-container-style u-custom-item u-list-item u-opacity u-opacity-40 u-radius u-repeater-item u-shape-round u-video-cover u-list-item-4\" data-animation-name=\"customAnimationIn\" data-animation-duration=\"1500\" data-animation-delay=\"250\">");
document.write("                        <div class=\"u-container-layout u-similar-container u-valign-middle u-container-layout-6\">");
document.write("                          <span class=\"u-custom-item u-file-icon u-hover-feature u-icon u-icon-4\" data-animation-name=\"customAnimationIn\" data-animation-duration=\"1500\" data-animation-delay=\"750\"><img src=\"images\/3334886.png\" alt=\"\"><\/span>");
document.write("                          <h4 class=\"u-text u-text-8\">react.js<\/h4>");
document.write("                          <a href=\"https:\/\/github.com\/topics\/react\" class=\"u-border-active-grey-70 u-border-black u-border-hover-grey-70 u-border-none u-bottom-left-radius-0 u-bottom-right-radius-0 u-btn u-button-style u-custom-item u-gradient u-none u-radius-0 u-text-active-white u-text-body-color u-text-hover-white u-top-left-radius-0 u-top-right-radius-0 u-btn-5\"> mais<\/a>");
document.write("                        <\/div>");
document.write("                      <\/div>");
document.write("                    <\/div>");
document.write("                  <\/div>");
document.write("                <\/div>");
document.write("              <\/div>");
document.write("            <\/div>");
document.write("          <\/div>");
document.write("        <\/div>");
document.write("      <\/div>");
document.write("    <\/section>");
document.write("    <section class=\"u-clearfix u-gradient u-section-2\" id=\"sec-2487\">");
document.write("      <div class=\"u-clearfix u-sheet u-sheet-1\"><\/div>");
document.write("    <\/section>");
document.write("    <section class=\"u-align-center u-clearfix u-custom-color-3 u-section-3\" id=\"sec-b1c4\">");
document.write("      <div class=\"u-clearfix u-sheet u-sheet-1\">");
document.write("        <h2 class=\"u-custom-font u-hover-feature u-text u-text-default u-text-1\"> Meus projetos<\/h2>");
document.write("        <div class=\"u-expanded-width u-layout-horizontal u-list u-list-1\">");
document.write("          <div class=\"u-repeater u-repeater-1\">");
document.write("            <div class=\"u-align-left u-black u-border-2 u-border-white u-container-style u-list-item u-opacity u-opacity-40 u-radius u-repeater-item u-shape-round u-list-item-1\">");
document.write("              <div class=\"u-container-layout u-similar-container u-container-layout-1\">");
document.write("                <img class=\"u-border-2 u-border-white u-expanded-width u-image u-image-round u-radius u-image-1\" alt=\"\" data-image-width=\"719\" data-image-height=\"1354\" src=\"images\/tm.jpg\" data-href=\"https:\/\/tmfibra.com.br\/\">");
document.write("                <h4 class=\"u-text u-text-custom-color-4 u-text-2\">");
document.write("                  <a class=\"u-active-none u-border-none u-btn u-button-link u-button-style u-hover-none u-none u-text-custom-color-4 u-btn-1\" data-href=\"https:\/\/tmfibra.com.br\/\">TM FIBRA<\/a>");
document.write("                <\/h4>");
document.write("                <p class=\"u-text u-text-body-alt-color u-text-3\"> PLANOS PARA VOCÊ, PARA SUA EMPRESA, E SEU CONDOMÍNIO Contrate a internet que cabe no seu bolso com muito mais GB<\/p>");
document.write("              <\/div>");
document.write("            <\/div>");
document.write("            <div class=\"u-align-left u-black u-border-2 u-border-white u-container-style u-list-item u-opacity u-opacity-40 u-radius u-repeater-item u-shape-round u-list-item-2\">");
document.write("              <div class=\"u-container-layout u-similar-container u-container-layout-2\">");
document.write("                <img class=\"u-border-2 u-border-white u-expanded-width u-image u-image-round u-radius u-image-2\" alt=\"\" data-image-width=\"719\" data-image-height=\"1354\" src=\"images\/conet.jpg\" data-href=\"https:\/\/conet-fibra.web.app\/\">");
document.write("                <h4 class=\"u-text u-text-custom-color-4 u-text-4\">");
document.write("                  <a class=\"u-border-none u-btn u-button-link u-button-style u-none u-text-custom-color-4 u-btn-2\" data-href=\"https:\/\/conet-fibra.web.app\/\" href=\"https:\/\/conet-fibra.web.app\/\"><b>CONET FIBRA<\/b>");
document.write("                  <\/a>");
document.write("                <\/h4>");
document.write("                <p class=\"u-text u-text-body-alt-color u-text-5\"> Com a CONET FIBRA, Você pode muito mais! O melhor da Internet no conforto da sua casa, simultaneamente e com quem você mais gosta.<\/p>");
document.write("              <\/div>");
document.write("            <\/div>");
document.write("            <div class=\"u-align-left u-black u-border-2 u-border-white u-container-style u-list-item u-opacity u-opacity-40 u-radius u-repeater-item u-shape-round u-list-item-3\">");
document.write("              <div class=\"u-container-layout u-similar-container u-container-layout-3\">");
document.write("                <img class=\"u-border-2 u-border-white u-expanded-width u-image u-image-round u-radius u-image-3\" alt=\"\" data-image-width=\"719\" data-image-height=\"1354\" src=\"images\/mae.jpg\" data-href=\"https:\/\/espacoconfortodospes.blogspot.com\/\">");
document.write("                <h4 class=\"u-text u-text-custom-color-4 u-text-6\">");
document.write("                  <a class=\"u-active-none u-border-none u-btn u-button-link u-button-style u-hover-none u-none u-btn-3\" href=\"https:\/\/espacoconfortodospes.blogspot.com\/\"> Espaço conforto dos pés<\/a>");
document.write("                <\/h4>");
document.write("                <p class=\"u-text u-text-body-alt-color u-text-7\"> Unha encravada Condição na qual o canto ou lado de uma unha cresce na carne.<\/p>");
document.write("              <\/div>");
document.write("            <\/div>");
document.write("            <div class=\"u-align-left u-black u-border-2 u-border-white u-container-style u-list-item u-opacity u-opacity-40 u-radius u-repeater-item u-shape-round u-list-item-4\">");
document.write("              <div class=\"u-container-layout u-similar-container u-container-layout-4\">");
document.write("                <img class=\"u-border-2 u-border-white u-expanded-width u-image u-image-round u-radius u-image-4\" alt=\"\" data-image-width=\"719\" data-image-height=\"1356\" src=\"images\/amin.jpg\" data-href=\"https:\/\/amindias.web.app\/\">");
document.write("                <h4 class=\"u-text u-text-custom-color-4 u-text-8\">");
document.write("                  <a class=\"u-active-none u-border-none u-btn u-button-link u-button-style u-hover-none u-none u-btn-4\" href=\"https:\/\/amindias.web.app\/\">amin<\/a>");
document.write("                <\/h4>");
document.write("                <p class=\"u-text u-text-body-alt-color u-text-9\"> Web Design Criador de site! Um criador de site profissional é uma ótima maneira de colocar seu negócio no ar sem precisar ter conhecimentos técnicos avançados.<\/p>");
document.write("              <\/div>");
document.write("            <\/div>");
document.write("            <div class=\"u-align-left u-black u-border-2 u-border-white u-container-style u-list-item u-opacity u-opacity-40 u-radius u-repeater-item u-shape-round u-list-item-5\">");
document.write("              <div class=\"u-container-layout u-similar-container u-container-layout-5\">");
document.write("                <img class=\"u-border-2 u-border-white u-expanded-width u-image u-image-round u-radius u-image-5\" alt=\"\" data-image-width=\"719\" data-image-height=\"950\" src=\"images\/paulo.jpg\">");
document.write("                <h4 class=\"u-text u-text-custom-color-4 u-text-10\">");
document.write("                  <a class=\"u-active-none u-border-none u-btn u-button-link u-button-style u-hover-none u-none u-btn-5\" href=\"https:\/\/pjxsantos.github.io\/\"> Portfólio Paulo jorge<\/a>");
document.write("                <\/h4>");
document.write("                <p class=\"u-text u-text-body-alt-color u-text-11\"> Toda vez que enfrento um “bloqueio”, ou preciso de uma dica, gosto de recorrer aos pensamentos brilhantes de Jeová...<\/p>");
document.write("              <\/div>");
document.write("            <\/div>");
document.write("          <\/div>");
document.write("          <a class=\"u-absolute-vcenter u-custom-color-4 u-gallery-nav u-gallery-nav-prev u-icon-circle u-opacity u-opacity-70 u-spacing-10 u-text-body-alt-color u-gallery-nav-1\" href=\"#\" role=\"button\">");
document.write("            <span aria-hidden=\"true\">");
document.write("              <svg viewBox=\"0 0 451.847 451.847\">");
document.write("                <path d=\"M97.141,225.92c0-8.095,3.091-16.192,9.259-22.366L300.689,9.27c12.359-12.359,32.397-12.359,44.751,0");
document.write("                  c12.354,12.354,12.354,32.388,0,44.748L173.525,225.92l171.903,171.909c12.354,12.354,12.354,32.391,0,44.744");
document.write("                  c-12.354,12.365-32.386,12.365-44.745,0l-194.29-194.281C100.226,242.115,97.141,234.018,97.141,225.92z\"><\/path>");
document.write("              <\/svg>");
document.write("            <\/span>");
document.write("            <span class=\"sr-only\">");
document.write("              <svg viewBox=\"0 0 451.847 451.847\">");
document.write("                <path d=\"M97.141,225.92c0-8.095,3.091-16.192,9.259-22.366L300.689,9.27c12.359-12.359,32.397-12.359,44.751,0");
document.write("                  c12.354,12.354,12.354,32.388,0,44.748L173.525,225.92l171.903,171.909c12.354,12.354,12.354,32.391,0,44.744");
document.write("                  c-12.354,12.365-32.386,12.365-44.745,0l-194.29-194.281C100.226,242.115,97.141,234.018,97.141,225.92z\"><\/path>");
document.write("              <\/svg>");
document.write("            <\/span>");
document.write("          <\/a>");
document.write("          <a class=\"u-absolute-vcenter u-custom-color-4 u-gallery-nav u-gallery-nav-next u-icon-circle u-opacity u-opacity-70 u-spacing-10 u-text-body-alt-color u-gallery-nav-2\" href=\"#\" role=\"button\">");
document.write("            <span aria-hidden=\"true\">");
document.write("              <svg viewBox=\"0 0 451.846 451.847\">");
document.write("                <path d=\"M345.441,248.292L151.154,442.573c-12.359,12.365-32.397,12.365-44.75,0c-12.354-12.354-12.354-32.391,0-44.744");
document.write("                  L278.318,225.92L106.409,54.017c-12.354-12.359-12.354-32.394,0-44.748c12.354-12.359,32.391-12.359,44.75,0l194.287,194.284");
document.write("                  c6.177,6.18,9.262,14.271,9.262,22.366C354.708,234.018,351.617,242.115,345.441,248.292z\"><\/path>");
document.write("              <\/svg>");
document.write("            <\/span>");
document.write("            <span class=\"sr-only\">");
document.write("              <svg viewBox=\"0 0 451.846 451.847\">");
document.write("                <path d=\"M345.441,248.292L151.154,442.573c-12.359,12.365-32.397,12.365-44.75,0c-12.354-12.354-12.354-32.391,0-44.744");
document.write("                  L278.318,225.92L106.409,54.017c-12.354-12.359-12.354-32.394,0-44.748c12.354-12.359,32.391-12.359,44.75,0l194.287,194.284");
document.write("                  c6.177,6.18,9.262,14.271,9.262,22.366C354.708,234.018,351.617,242.115,345.441,248.292z\"><\/path>");
document.write("              <\/svg>");
document.write("            <\/span>");
document.write("          <\/a>");
document.write("          <a class=\"u-absolute-vcenter-lg u-absolute-vcenter-xl u-custom-color-4 u-gallery-nav u-gallery-nav-prev u-hidden-sm u-icon-circle u-opacity u-opacity-70 u-spacing-10 u-text-body-alt-color u-gallery-nav-3\" href=\"#\" role=\"button\">");
document.write("            <span aria-hidden=\"true\">");
document.write("              <svg viewBox=\"0 0 451.847 451.847\">");
document.write("                <path d=\"M97.141,225.92c0-8.095,3.091-16.192,9.259-22.366L300.689,9.27c12.359-12.359,32.397-12.359,44.751,0");
document.write("                  c12.354,12.354,12.354,32.388,0,44.748L173.525,225.92l171.903,171.909c12.354,12.354,12.354,32.391,0,44.744");
document.write("                  c-12.354,12.365-32.386,12.365-44.745,0l-194.29-194.281C100.226,242.115,97.141,234.018,97.141,225.92z\"><\/path>");
document.write("              <\/svg>");
document.write("            <\/span>");
document.write("            <span class=\"sr-only\">");
document.write("              <svg viewBox=\"0 0 451.847 451.847\">");
document.write("                <path d=\"M97.141,225.92c0-8.095,3.091-16.192,9.259-22.366L300.689,9.27c12.359-12.359,32.397-12.359,44.751,0");
document.write("                  c12.354,12.354,12.354,32.388,0,44.748L173.525,225.92l171.903,171.909c12.354,12.354,12.354,32.391,0,44.744");
document.write("                  c-12.354,12.365-32.386,12.365-44.745,0l-194.29-194.281C100.226,242.115,97.141,234.018,97.141,225.92z\"><\/path>");
document.write("              <\/svg>");
document.write("            <\/span>");
document.write("          <\/a>");
document.write("          <a class=\"u-absolute-vcenter u-custom-color-4 u-gallery-nav u-gallery-nav-next u-icon-circle u-opacity u-opacity-70 u-spacing-10 u-text-body-alt-color u-gallery-nav-4\" href=\"#\" role=\"button\">");
document.write("            <span aria-hidden=\"true\">");
document.write("              <svg viewBox=\"0 0 451.846 451.847\">");
document.write("                <path d=\"M345.441,248.292L151.154,442.573c-12.359,12.365-32.397,12.365-44.75,0c-12.354-12.354-12.354-32.391,0-44.744");
document.write("                  L278.318,225.92L106.409,54.017c-12.354-12.359-12.354-32.394,0-44.748c12.354-12.359,32.391-12.359,44.75,0l194.287,194.284");
document.write("                  c6.177,6.18,9.262,14.271,9.262,22.366C354.708,234.018,351.617,242.115,345.441,248.292z\"><\/path>");
document.write("              <\/svg>");
document.write("            <\/span>");
document.write("            <span class=\"sr-only\">");
document.write("              <svg viewBox=\"0 0 451.846 451.847\">");
document.write("                <path d=\"M345.441,248.292L151.154,442.573c-12.359,12.365-32.397,12.365-44.75,0c-12.354-12.354-12.354-32.391,0-44.744");
document.write("                  L278.318,225.92L106.409,54.017c-12.354-12.359-12.354-32.394,0-44.748c12.354-12.359,32.391-12.359,44.75,0l194.287,194.284");
document.write("                  c6.177,6.18,9.262,14.271,9.262,22.366C354.708,234.018,351.617,242.115,345.441,248.292z\"><\/path>");
document.write("              <\/svg>");
document.write("            <\/span>");
document.write("          <\/a>");
document.write("        <\/div>");
document.write("      <\/div>");
document.write("    <\/section>");
document.write("    <section class=\"u-clearfix u-gradient u-section-4\" id=\"sec-a6b1\">");
document.write("      <div class=\"u-clearfix u-sheet u-sheet-1\"><\/div>");
document.write("    <\/section>");
document.write("    <section class=\"u-align-center u-clearfix u-container-align-center u-gradient u-section-5\" id=\"carousel_c8ff\">");
document.write("      <div class=\"u-clearfix u-sheet u-sheet-1\">");
document.write("        <h2 class=\"u-custom-font u-hover-feature u-text u-text-body-alt-color u-text-default u-text-1\">Biografia<\/h2>");
document.write("        <div class=\"u-align-center u-black u-border-2 u-border-white u-container-style u-expanded-width-sm u-expanded-width-xs u-group u-opacity u-opacity-40 u-radius u-shape-round u-group-1\" data-animation-name=\"customAnimationIn\" data-animation-duration=\"1500\" data-animation-delay=\"0\">");
document.write("          <div class=\"u-container-layout u-container-layout-1\">");
document.write("            <h2 class=\"u-text u-text-default u-text-2\"> Recorram a Jeová Deus<\/h2>");
document.write("            <p class=\"u-text u-text-default u-text-3\"> Toda vez que enfrento um “bloqueio”, ou preciso de uma dica, gosto de recorrer aos pensamentos brilhantes de Jeová ele sim sabe resumir informações poderosas em poucas palavras.<\/p>");
document.write("            <a href=\"https:\/\/www.jw.org\/pt\/ensinos-biblicos\/textos-biblicos\/isaias-41-10\/\" class=\"u-active-white u-align-center u-border-active-white u-border-hover-white u-border-none u-btn u-btn-round u-button-style u-gradient u-hover-feature u-hover-white u-none u-radius u-text-active-white u-text-hover-black u-text-white u-btn-1\"> Isaías 41:10<span style=\"font-weight: 700;\"><\/span>");
document.write("            <\/a>");
document.write("          <\/div>");
document.write("        <\/div>");
document.write("      <\/div>");
document.write("    <\/section>");
document.write("    <footer class=\"u-black u-clearfix u-footer\" id=\"sec-22b6\">");
document.write("      <div class=\"u-clearfix u-sheet u-sheet-1\">");
document.write("        <a href=\"#\" class=\"u-hover-feature u-image u-logo u-image-1\" data-image-width=\"376\" data-image-height=\"245\" data-animation-name=\"customAnimationIn\" data-animation-duration=\"1000\" title=\"#\">");
document.write("        <img src=\"images\/1703183666890logo.png\" class=\"u-logo-image u-logo-image-1\">");
document.write("        <\/a>");
document.write("        <div class=\"u-align-left u-hover-feature u-social-icons u-spacing-10 u-social-icons-1\" data-animation-name=\"customAnimationIn\" data-animation-duration=\"1000\">");
document.write("          <a class=\"u-social-url\" title=\"Github\" target=\"_blank\" href=\"https:\/\/github.com\/Pjxsantos\/\"><span class=\"u-file-icon u-icon u-social-facebook u-social-icon u-text-white u-icon-1\"><img src=\"images\/2111432-3e937c4e.png\" alt=\"\"><\/span>");
document.write("          <\/a>");
document.write("          <a class=\"u-social-url\" title=\"Mapa Cutural\" target=\"_blank\" href=\"https:\/\/www.mapacultural.pe.gov.br\/agente\/21825\/\"><span class=\"u-file-icon u-icon u-social-icon u-social-twitter u-text-white u-icon-2\"><img src=\"images\/2538758-414c452b.png\" alt=\"\"><\/span>");
document.write("          <\/a>");
document.write("          <a class=\"u-social-url\" title=\"instagram\" target=\"_blank\" href=\"\"><span class=\"u-file-icon u-icon u-social-icon u-social-instagram u-text-white u-icon-3\"><img src=\"images\/1384015-98ffe3a1.png\" alt=\"\"><\/span>");
document.write("          <\/a>");
document.write("          <a class=\"u-social-url\" title=\"linkedin\" target=\"_blank\" href=\"https:\/\/www.linkedin.com\/in\/pjxsantos\/\"><span class=\"u-file-icon u-icon u-social-icon u-social-linkedin u-text-white u-icon-4\"><img src=\"images\/1384014-bd602818.png\" alt=\"\"><\/span>");
document.write("          <\/a>");
document.write("        <\/div>");
document.write("        <div class=\"u-border-1 u-border-white u-expanded-width u-line u-line-horizontal u-opacity u-opacity-50 u-line-1\"><\/div>");
document.write("        <p class=\"u-align-center u-text u-text-1\"> Copyright © 2023 – Todos os Direitos Reservados.<\/p>");
document.write("      <\/div>");
document.write("    <\/footer>");
document.write("    <span style=\"height: 64px; width: 64px; margin-left: 0px; margin-right: auto; margin-top: 0px; background-image: none; right: 20px; bottom: 20px; padding: 15px; box-shadow: -1px -1px 20px 0 rgba(255,255,255,0.4); text-shadow: -1px -1px 0 rgba(0,0,0,0);\" class=\"u-back-to-top u-custom-color-5 u-icon u-icon-circle u-opacity u-opacity-65\" data-href=\"#\">");
document.write("      <svg class=\"u-svg-link\" preserveAspectRatio=\"xMidYMin slice\" viewBox=\"0 0 551.13 551.13\">");
document.write("        <use xmlns:xlink=\"http:\/\/www.w3.org\/1999\/xlink\" xlink:href=\"#svg-1d98\"><\/use>");
document.write("      <\/svg>");
document.write("      <svg class=\"u-svg-content\" enable-background=\"new 0 0 551.13 551.13\" viewBox=\"0 0 551.13 551.13\" xmlns=\"http:\/\/www.w3.org\/2000\/svg\" id=\"svg-1d98\">");
document.write("        <path d=\"m275.565 189.451 223.897 223.897h51.668l-275.565-275.565-275.565 275.565h51.668z\"><\/path>");
document.write("      <\/svg>");
document.write("    <\/span>");
document.write("  <\/body>");
document.write("<\/html>");
